### ISSUE TITLE
Crash when "don't keep activities is enabled"

### ISSUE THREAD

**Issue by gmbett** [ionic-team/portals-ecommerce-demo#55]
Hi, I'm just checking this demo app and I noticed the following crash when don't keep activities is enabled (from Android developer options):

`java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.FragmentManager io.ionic.demo.ecommerce.MainActivity.getSupportFragmentManager()' on a null object reference
        at io.ionic.demo.ecommerce.ui.store.StoreContainerFragment.onCreateView(StoreContainerFragment.java:42)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2961)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:504)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1324)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2715)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2658)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
        at android.app.Activity.performStart(Activity.java:8076)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3664)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by cmveas** [comment]
I also experience this on a pet project I'm working on. I have it when using a fragment that extends PortalFragment(but also happened in an activity that contains a portal in the layout). We use a library that internally does a call to startActivityForResult and the crash happens when the result is returned. 

In order to avoid the crash I used the following code but I think this might go into a place inside the PortalFragment implementation

```
class LoginFragment : PortalFragment {
    constructor() : super() {}
    constructor(portal: Portal?) : super(portal) {}

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        if (**activity != null && portal!=null)** {
            super.onViewCreated(view, savedInstanceState)
            setHasOptionsMenu(false)
        }
    }
```

**Comment by carlpoole** [comment]
Thanks for the report. We will fix this in a future update
